name: Checks
on:
  pull_request:
  push:
    branches: [main]
permissions:
  contents: read
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - uses: cachix/install-nix-action@v31.11.1
      - uses: cachix/cachix-action@v17
        with:
          name: devenv
      - run: nix profile add github:cachix/devenv/v2.4.0
      - run: devenv test
